### ISSUE TITLE
where can I download OSDMeasure.min.js

### ISSUE THREAD

**Issue by chengdonglin** [verrochi92/OSDMeasure#6]
I not find the OSDMeasure.min.js in repo?

**Comment by verrochi92** [comment]
So because the library uses many classes within many files, to get the minified .js file, please download the 1.0 release - this even includes the other dependencies. I'm considering adding it to the main repo as well just for ease of access

**Comment by verrochi92** [comment]
You can see the contents of the release version [here](https://github.com/verrochi92/OSDMeasure/tree/release) and I'll close the issue when I've moved everything into the main branch

**Comment by verrochi92** [comment]
Just wanted to follow up on this, I realized there is no OSDMeasure.min.js, rather just OSDMeasure.js - I will fix the documentation
